name: Kanvas Screenshot Service
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:
    inputs:
      fileName:
        description: Relative file path from the root directory
        required: true
        type: string
    outputs:
      resource_url:
        description: The URL of the generated resource.
        value: ${{ jobs.KanvasScreenshot.outputs.resource_url }}
permissions:
  actions: read
  contents: write
  security-events: write
  statuses: write
  pull-requests: write
  id-token: write
jobs:
  KanvasScreenshot:
    runs-on: ubuntu-latest
    outputs:
      resource_url: ${{ steps.test_result.outputs.resource_url }}
    steps:
      - name: Set PR number
        run: |
          export pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NO=$pull_number" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: action
          repository: layer5labs/kanvas-snapshot
      - id: test_result
        uses: layer5labs/kanvas-snapshot@v0.2.35
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mesheryToken: ${{ secrets.MESHERY_TOKEN }}
          prNumber: ${{ env.PULL_NO }}
          application_type: Kubernetes Manifest
          filePath: ${{ inputs.fileName == '' && 'catalog/0194ff83-0a43-4b83-9c75-b8f0f32da6b7/0.0.1/design.yml' || inputs.fileName }}
